trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
      - "*.md"
pr:
  paths:
    exclude:
      - "*.md"

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-20.04'
        python.version: '3.6'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python311Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - task: DeleteFiles@1
    inputs:
      contents: "spacy_transformers"
    displayName: "Delete source directory"

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: "Uninstall all packages"

  - script: |
      pip install "torch==1.8.1+cpu" -f https://download.pytorch.org/whl/torch_stable.html
    displayName: 'Install oldest supported torch for python 3.6'
    condition: eq(variables['python.version'], '3.6')

  - bash: |
      SDIST=$(python -c "import os;print(os.listdir('./dist')[0])" 2>&1)
      python -m pip install dist/$SDIST
    displayName: 'Install from sdist'

  - script: |
      pip install -r requirements.txt
      python -m pytest --pyargs spacy_transformers --cov=spacy_transformers
    displayName: 'Run tests'

  - script: |
      pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.1.0/en_core_web_trf-3.1.0-py3-none-any.whl --no-deps
      python -c "import spacy; nlp = spacy.load('en_core_web_trf'); doc = nlp('test')"
    displayName: 'Test backwards compatibility for v1.0 models'
